apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  # Полный аудит операций с подами в audit-zone
  - level: RequestResponse
    namespaces: ["audit-zone"]
    resources:
      - group: ""
        resources: ["pods"]
    verbs: ["create", "update", "patch", "delete"]

  # Изменения политик безопасности и Gatekeeper
  - level: RequestResponse
    resources:
      - group: "constraints.gatekeeper.sh"
        resources: ["*"]
      - group: "templates.gatekeeper.sh"
        resources: ["*"]
      - group: ""
        resources: ["namespaces"]
    verbs: ["create", "update", "patch", "delete"]

  # Остальное — метаданные без тела запроса
  - level: Metadata
    omitStages:
      - RequestReceived
